trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*.*
  paths:
    exclude:
    - README.md

pr: none

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: 'Generate nuspec from module manifest'
  inputs:
    filePath: 'Get-NuspecFromManifest.ps1'
    arguments: '-BuildNumber $(Build.BuildNumber)'

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: 'pack'
    packagesToPack: 'PoShKeePass.nuspec'
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'e5dd384e-3968-4fc3-acfc-455895816fb2'